version: '3'
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'biniou'
      MYSQL_ROOT_PASSWORD: 'biniou'
  web:
    build: .
    ports:
      - 3000:8080
    environment:
      PORT: 8080
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: biniou
    volumes:
      - .:/app
